spring.application.name=subscription-billing
spring.datasource.url=jdbc:mysql://mysql-21c23f9a-pandeydivyani3021-896c.h.aivencloud.com:21335/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true